Feature/spending sorting
everjupe13/dicoin-project pull request #21
Opened 2024-12-24 12:15 UTC by mnogodumal

2024-12-30 12:40 UTC, everjupe13 reviewed
Все еще нет функционала для выставления сортировки при переходу по прямому урлу, например если я перейду по spendings?slug=withdrawal-date-ascending то в селекте должен быть выбран вариант "По убыванию списания"

Также убери весь функционал со сортировкой на стороне фронта, это все будет регулироваться со стороны сервера, тебе всего лишь нужно будет передавать нужные параметры в запрос , в данном случае можешь передавать в fetchSpendingsPaginated и либо не делать вообще сортировки , либо реализовать ее там, не внося функцию в модуль

2024-12-30 12:40 UTC, everjupe13 commented on src/components/spendings/spending-sorting/ui/SpendingSorting.tsx
Давай переименуем в Spendings по названию пакета, а файл будет именовать в kebab case, как и другие модули в фиче spendings

2024-12-30 12:40 UTC, everjupe13 commented on src/components/spendings/spending-sorting/ui/SpendingSorting.tsx
> +  const DATA = [
это нужно вынести за компонент, или лучше в корневой компонент (там где будет происходить фетч данных)

2024-12-30 12:40 UTC, everjupe13 commented on src/components/spendings/spending-sorting/ui/SpendingSorting.tsx
> +        name="MyName"
name или убери или поставь что-то значимое

2024-12-30 12:40 UTC, everjupe13 commented on src/components/spendings/spending-sorting/ui/SpendingSorting.tsx
> +  onSortChange: (slug: string) => void
вынеси в интерфейс по аналогии с другими твоими модулями

2024-12-30 12:40 UTC, everjupe13 commented on src/components/spendings/spending-sorting/ui/SpendingSorting.tsx
> +  onSortChange: (slug: string) => void
сделай необязательным

2024-12-30 12:40 UTC, everjupe13 commented on src/pages/SpendingsPage.tsx
> +  data: ISpendings[],
почему для получения листа айтемов нужно передавать лист айтемов ?

2024-12-30 12:40 UTC, everjupe13 commented on src/pages/SpendingsPage.tsx
> +  const [currentPage, setCurrentPage] = useState<number>(1)
number в generic useState передавать необязательно, так как есть дефолтное значение уже являющееся числом, ts подхватит тип

2025-01-09 18:45 UTC, everjupe13 commented on src/pages/SpendingsPage.tsx
> +  const sortedData = useMemo(() => {
вроде лишнее, стоит удалить

2025-01-09 18:45 UTC, everjupe13 commented on src/pages/SpendingsPage.tsx
> +    setSearchParams({ slug: slug })
если на текущей странице уже будет установлен какой-то параметр и ты сменишь значение в сортировке, то он удалится и поставится только этот. попробуй например перейти по /spendings?modal=asd и выставить параметр в сортировке

2025-01-09 18:45 UTC, everjupe13 commented on src/pages/SpendingsPage.tsx
> +  const sortSlug = searchParams.get('slug') || null
давай будет использовать вместо slug ключ sorting, и вынесем его в константу, пока можно в этом же файле

2025-01-09 18:45 UTC, everjupe13 commented on src/components/spendings/spendings-sorting/utils/Sorting.ts
> +export function sortSpendings(
это же лишнее - не используется, можно удалить

2025-01-09 19:01 UTC, everjupe13 commented on src/components/spendings/spendings-sorting/ui/spendings-sorting.tsx
> +interface MockSortingProps {
Убери из названия типа Mock, и перемести его в @/api/types

2025-01-09 19:07 UTC, everjupe13 commented on src/components/spendings/spendings-sorting/ui/spendings-sorting.tsx
> +  const selectedOption =
здесь можно не использовать || undefined, так как find вернет undefined если не найдет ни одного вхождения
лучше сделать проверку на сам currentSlug вдруг придет с сервера дата, где опшион будет, а value у него будет undefined, тогда find вернет этот опшион и он станет selected, что не корректно

думаю можно переписать так 

  const selectedOption = currentSlug
    ? options.find(option => option.value === currentSlug)
    : undefined

2025-01-09 19:09 UTC, everjupe13 commented on src/components/spendings/spendings-sorting/ui/spendings-sorting.tsx
> +  const options = sortingData.flatMap(data =>
давай сделаем проверку для options, вдруг дата придет с сервера некорретно и будет пустой массив для values

нужно проверить длину options и вернуть из компонента null если она нулевая

2025-01-10 11:52 UTC, mnogodumal commented on src/components/spendings/spendings-sorting/utils/Sorting.ts
> +export function sortSpendings(
Пиздец обидно, столько писал

2025-01-10 16:32 UTC, everjupe13 requested changes

2025-01-10 16:32 UTC, everjupe13 commented on src/api/types/SortingProps.ts
> +export interface SortingProps {
Давай назовем ISorting - это тип общий для любой сортировки какая у нас будет

2025-01-10 16:32 UTC, everjupe13 commented on src/api/types/SortingProps.ts
> +export interface SortingProps {
Файл соответсвенно тоже

2025-01-10 16:32 UTC, everjupe13 commented on src/components/spendings/spendings-sorting/index.ts
> +export { SpendingsSorting } from './ui/spendings-sorting'
```suggestion
export * from './ui/spendings-sorting'
```

2025-01-10 16:32 UTC, everjupe13 commented on src/pages/SpendingsPage.tsx
> +    setSearchParams(prev => ({ ...Object.fromEntries(prev), slug }))
setSearchParams(prev => ({ ...Object.fromEntries(prev), [sorting]: slug }))

2025-01-10 16:32 UTC, everjupe13 commented on src/pages/SpendingsPage.tsx
> +const sorting = 'slug'
const sorting = 'sorting'

2025-01-10 16:32 UTC, everjupe13 commented on src/pages/SpendingsPage.tsx
> +        currentSlug={sortSlug}
а если такого значения не будет, если я перейду по ссылке где будет ?sorting=not-valid-value что-то может сломаться, давай обработаем этот кейс

2025-01-10 16:32 UTC, everjupe13 commented on src/pages/SpendingsPage.tsx
>      [currentPage]
давай добавим в массив зависимостей sortSlug, так как функция и вообще дата от нее зависит

2025-04-06 18:08 UTC, merged